### ISSUE TITLE
Typesafe Activators for Akka

### ISSUE THREAD

**Issue by pawelpanasewicz** [softwaremill/macwire#113]
Typesafe Activators for Akka can be now implemented using `akkaSupport` module.

https://typesafe.com/activator/template/macwire-akka-activator

**Comment by ktoso** [comment]
"Activator will be EOL-ed on May 24, 2017."

So I suggest to close this issue.

Rather you should use g8 so `sbt new` can pick up such repo :) like here https://github.com/akka/akka-quickstart-scala.g8
