### ISSUE TITLE
Add support for Akka Typed

### ISSUE THREAD

**Issue by renatocaval** [softwaremill/macwire#145]
We are adding dependency injection for Akka Typed in Play (https://github.com/playframework/playframework/pull/8999) and it will be cool to have the same in Macwire.

**Comment by adamw** [comment]
Would you need anything specific from the macwire side? As long as there are constructors, macwire should work

**Comment by renatocaval** [comment]
There are a few things needed in Akka Typed. 

The first thing is how we create the actor. It's not via a constructor, but using a method that returns a Behaviour. Actually a factory function.

This example is extracted from Akka docs.

```scala
object HelloWorldBot {

  def bot(greetingCounter: Int, max: Int): Behavior[HelloWorld.Greeted] =
    Behaviors.receive { (context, message) =>
      val n = greetingCounter + 1
      context.log.info("Greeting {} for {}", n, message.whom)
      if (n == max) {
        Behaviors.stopped
      } else {
        message.from ! HelloWorld.Greet(message.whom, context.self)
        bot(n, max)
      }
    }
}
```

In a real DI example, that method would receive other dependencies wired by macwire.

The other issue to solve is how to really get an instance of `ActorRef[HelloWorld.Greeted]`.

There are two ways of doing it. Using a Typed ActorSystem or the Classic (untyed) ActorSystem.

When using untyped, we can create it as a child of another actor but then you don't need DI or you create it directly on the actor system as a top-level one. 

```scala
val system = untyped.ActorSystem("TypedWatchingUntyped")
val typed = system.spawn(HelloWorldBot.bot(0, 10), "Typed")
```

When using the Typed ActorSystem, you can only create it as a child. Actually, the pattern to follow is to have one Typed ActorSystem bootstrapping your whole application. 

Here is an example of it: https://github.com/chbatey/akka-http-typed/blob/master/src/main/scala/info/batey/QuickstartServer.scala

Note how the whole app is bootstrapped by a user top-level actor. All actors created in that application will be created from that parent actor context. 

In Play, we will only be supporting the untyped variant for now. The typed variant will require a huge Play refactoring. We will need a typed actor system that wraps the whole Play app. That's for later.

**Comment by adamw** [comment]
For the `HelloWorldBot` example, I think any dependencies would be expressed by constructor parameteres,e.g.:

```
class HelloWorldBot(service: MyService) {
  def bot(greetingCounter: Int, max: Int): Behavior[HelloWorld.Greeted] = ...
}
```

and then you can call the behavior-creating method, which can of course use the service. Nice and simple, nothing akka-specific. A `Behavior` is just a description that can use whatever's in its surrounding scope.

Injecting dependencies to methods ... well this just sounds like adding additional parameters?

I suppose I would need a more specific example (maybe with Guice) so that I could see how macwire could help here :)

**Comment by renatocaval** [comment]
The PR I linked here is for Guice. Have a look on [ActorModule](https://github.com/playframework/playframework/pull/8999/files#diff-159d518842dbdfc5550c4ff5d9b186a8R42).

But I just realised one thing. This kind of dependency injection infrastructure is needed for runtime DI. For compile-time DI, it's probably overkill. 

If I have a cake component that provides me with an `ActorSystem`, I can simply add a line like:

```scala
lazy val botActor: ActorRef[HelloWorld.Greeted] = 
  system.spawn(HelloWorldBot.bot(0, 10, service), "Typed")
```

Now I have my reference to `botActor` in scope and I can let Macwire inject it where I need. 

I think we can close this. Let me know if I'm missing something. Maybe there are some other advantages to have it wired by Macwire that I'm missing. 

Closing for now...

**Comment by adamw** [comment]
I think the main benefit is not having runtime DI/Guice ;) Be it with macwire or just using constructors directly.

But yes, I think you can just have a `botActor` dependency defined as bove. That's what I would do.

**Comment by kevinkyyro** [comment]
Indeed, the functional-style typed actors have no need for special support, but the OOP-style typed actors could benefit a bit.

Consider [this example](https://github.com/akka/akka/blob/v2.6.6/akka-actor-typed-tests/src/test/scala/docs/akka/typed/StyleGuideDocExamples.scala#L21-L96), which I'll modify a bit here:
```scala
class Counter(context: ActorContext[Counter.Command], db: Database, mailer: EmailClient) 
  extends AbstractBehavior[Counter.Command](context) 
{
  override def onMessage(msg: Counter.Command): Behavior[Counter.Command] = ???
}
```

To wire it up, we need to use `Behaviors.setup`:
```scala
// without macwire
Behaviors.setup(context => new Counter(context, db, mailer))

// with macwire
Behaviors.setup[Counter.Command](context => wire[Counter])

// would be nice if it could be
Behaviors.setup(context => wire[Counter]) // doesn't compile:  missing parameter type

// would be great if it could be
wireBehavior[Counter]
```

🤷‍♂️
