### ISSUE TITLE
Add support for the `@Module` annotation

### ISSUE THREAD

**Issue by mbore** [softwaremill/macwire#172]

**Comment by willisjtc** [comment]
is there any work being done to make macwire feature complete with scala 3?

**Comment by mbore** [comment]
Yes, I'm currently working on it and hope that initial support will be released in the following week.

**Comment by willisjtc** [comment]
hi @mbore , any updates?

**Comment by mbore** [comment]
Hey, thanks for the ping. I've just managed to finish the initial implementation so once it's reviewed, I'll release it. We're currently not able to support `@Module` in Scala 3 exactly the same way as we support in Scala 2, because of a few other issues (e.g. #169 and #168), but the core of the feature works as expected. 
[Here](https://github.com/softwaremill/macwire/issues/169) you can find some examples - Scala 3 implementation does not work for tests that end with `*.scala2.[success/failure]`. Please let me know if any of them is a blocker for you
