### ISSUE TITLE
Error if a provided instance/resource/... is unused

### ISSUE THREAD

**Issue by adamw** [softwaremill/macwire#182]
If some type is provided explicitly, it's probably a bug that it's not used.

However, we can also consider making this configurable somehow, so that a warning only might be emitted (maybe useful for development?)

**Comment by mbore** [comment]
resolved in #188 
test - https://github.com/softwaremill/macwire/pull/188/files#diff-d149dfa4c95202c6d1fc4e6f6f078fa535468cb65b1d5662085ebf5688868fc6
