### ISSUE TITLE
call-by-name parameter support in wireWith

### ISSUE THREAD

**Issue by an-tex** [softwaremill/macwire#187]
Would this be possible just like for `wire` (https://github.com/softwaremill/macwire/issues/18 / https://github.com/softwaremill/macwire/pull/29)?

As is I'm getting a `Cannot find a value of type: [=> MyDependency]`

Update:
minimal example:
```scala
import com.softwaremill.macwire._

class Dependency

object Component {
  // removing the => makes it compile
  def create(dependency: => Dependency) = 1
}

object Wiring {
  val dependency = wire[Dependency]
  val component = wireWith(Component.create _)
}

Wiring.component
```

motivation: circular dependency between components

**Comment by mbore** [comment]
It's definitely a good idea. It seems that we also do not support call-by-name parameters in factory methods e.g. 
```Scala
class Dependency(val s: String)

class Component private (s: String)

object Component {
  def apply(dependency: => Dependency) = new Component(dependency.s)
}

object Wiring {
  val dependency = new Dependency("s")
  val component = wire[Component]
}

Wiring.component
 
```

Before we start work on that, we need to complete #186, since it's going to have an impact on crimpers.

**Comment by mbore** [comment]
It's currently implemented only for Scala2. Scala 3 version is blocked by https://github.com/lampepfl/dotty/issues/14236

**Comment by an-tex** [comment]
awesome thanks a lot @mbore ! I'll test it next week
