### ISSUE TITLE
Imlement pure autowire

### ISSUE THREAD

**Issue by mbore** [softwaremill/macwire#191]
Autowire should not require using any effect library, so we should extract the core logic of the feature to the `macros` module.
Integrations with catsEffect or ZIO should be added in separate modules.

**Comment by djx314** [comment]
Hi, I provide some suggestion and some sampels about wire in gitter. Thank you for your attention to this proposal.

**Comment by djx314** [comment]
Hi @mbore , I provide some suggestion and some sampels about wire in gitter. Thank you for your attention to this proposal.
