### ISSUE TITLE
Need help: implement wireImplicit.

### ISSUE THREAD

**Issue by djx314** [softwaremill/macwire#273]
<https://scastie.scala-lang.org/djx314/6B1sptQ8QiywZcpciSlgHg/94>

I have implemented a `circe` `(En/De)coder` in a simple way in this sample.

See some code
```scala
case class CirceModel(name: String, id: Long, age: Int, nick: String) // Model in when you are developing.
class TestModel[Ctx[_]] {
  case class CirceModel(name: Ctx[String], id: Ctx[Long], age: Ctx[Int], nick: Ctx[String])  // Model in this sample.
}
```
In this sample, `CirceModel` is `TestModel[Id]#CirceModel`, `Encoder[CirceModel]` is `TestModel[Encoder]#CirceModel` and `Decoder[CirceModel]` is `TestModel[Decoder]#CirceModel`.

And `slick` is just `TestModel[Id]#CirceModel`, `TestModel[Rep]#CirceModel` and `TestModel[Shapel[FlatShapeLevel, Rep[*], _, _]]#CirceModel`, and then just throw it to runtime and no need compile time any more.

So all is `TestModel[Ctx[_]]`, but it's hard to translate it to
```scala
class TestModelDecoder(implicit name: Decoder[String], id: Decoder[Long], age: Decoder[Int], nick: Decoder[String]) extends TestModel[Decoder]#CirceModel(name = name, id = id, age = age, nick = nick)
```
and it's not the best practices.

I wonder if it can translate to something that in `macwire` like
```scala
val ctx = new TestModel[Decoder]
object TestModelDecoder {
  def input(name: Decoder[String] = implicitly, id: Decoder[Long] = implicitly, age: Decoder[Int] = implicitly, nick: Decoder[String] = implicitly): ctx.CirceModel = ctx.CirceModel(name = name, id = id, age = age, nick = nick)
}
```
so that I can
```scala
val ctx = wire[TestModel[Decoder]]
implicit val decoderImpl: Decoder[ctx.CirceModel] = translateDecoder(wireImplicit[ctx.CirceModel].input(age = CusDecoder.myIntDecoder.notToUseSnakeName.defaultValue(2), id = Decoder.from[Long].filter(i => i > 0)))
```

Injection, generic, refined, slick, the `Meta` of `Model`, and the `Model` itself, all is `TestModel[Ctx[_]]#CirceModel`.

**Comment by djx314** [comment]
Finally, just make each parameter in `case class`'s `def apply` that getting by type is ok.  
Get by type in scala is implicit(or `shapeless`), and `macwire` is `I want to get by type but "implicit not found."`, so there is noting to do with this issue.

**Comment by djx314** [comment]
Can be closed if needed.

**Comment by adamw** [comment]
Ok, I'm not quite sure I understand the problem, but if it's solved, all the better :)

**Comment by djx314** [comment]
@adamw Reopen the issue since reproduct the problem.
I use `macwire` to implement a `injection` in` cats-effect` with a simple way.
And it seems that it works in any effect type.
But some code not works well.
[Code Link](https://github.com/scalax/simple/blob/45878de4432933c4094a559e8dd84dbbcf1e447d/modules/main/simple-wire/web-app-scala-style/src/main/scala/net/scalax/simple/wire/constructor/AppWire.scala#L21-L22)
`Line 20` and `Line 21` can not use `macwire` since "injection by name" is the same as "injection by varible name" in this injection style. Hoping for help to make these code more friendly.
